### ISSUE TITLE
Research Project 1 Topics

### ISSUE THREAD

**Issue by bongjunj** [gdsc-kaist/gdsc-kaist.github.io#2]
List your topics for research project 1.

* Midterm Presentation: Nov 17th
* Final Presentation: Dec 21th

**Comment by bongjunj** [comment]
Super Tiny Compiler (https://github.com/bonjune/super-tiny-compiler)

아주 간단한 컴파일러 만들기

- Tokenization, AST, Code generation 기능 구현하기
- 구현에 필요한 지식 정리하기

컴파일러는 입력 문자열을 정해진 언어의 문법과 규칙에 따라 분석해 실행가능한 파일을 생성하는 프로그램이다. CS320에서 사용되는 FVAE 언어의 문법을 이용해 문자열의 Tokenization, Parsing, Interpreter, Code Generation 등 컴파일러와 관련된 기능을 하나씩 구현할 예정이다.

**Comment by seo-rii** [comment]
번들러의 역사

* 번들러가 뭔지, 그리고 어떻게 작동하는지 알아보고 어떻게 개선되어 왔는지 알아보기
* 간단한 번들러 만들어보기

**Comment by gahyeon111** [comment]
크롬 V8 자바스크립트 엔진의 동작 과정
- 동작 pipeline
- 부분 코드 분석

자바스크립트 개발자라면 V8 엔진에 대해 한 번쯤은 들어봤을 거라 생각한다. V8 엔진은 C++로 작성된 고성능의 오픈소스 자바스크립트 엔진으로, 현재 Google Chrome과 Node.js에서 사용되고 있다. 이러한 V8 엔진의 동작 과정 분석을 통해 자바스크립트 코드가 어떻게 실행되는지 알아보고자 한다.

**Comment by seo-rii** [comment]
Future of Opensource

오픈소스로 인해 프로그래밍 업계가 어떻게 변했는지 알아보고, 오픈소스에서 벌어진 사건들에 대해 알아보고, 앞으로 오픈소스가 어떠한 길을 추구해야 할지 알아보기

**Comment by seo-rii** [comment]
Goodbye, GIL!

파이썬 3.11에서 삭제된 GIL이 무엇인지 알아보고, 어떻게 이를 비활성화했는지(대부분의 상황에서) 코드를 보며 알아보기

**Comment by iamyouno** [comment]
여러 브라우저에 따라 사진/영상의 랜더링 차이

- 브라우저가 response를 받아 온 시점부터 어떤 일이 벌어지는지
- (브라우저의 작동원리)

아마 웹 브라우저에 대해 다들 잘 알고 있을 것입니다. 크롬, 네이버 웨일, 사파리 등이 대표적인 예입니다. 웹 브라우저가 웹 서퍼에, 필요한 웹 페이지를 요청하면 서버는 응답하고, 웹 브라우저는 이를 해석하여 사용자에게 보여줍니다. 우리는 이 해석하는 과정에, 특히 이미지와 영상이 해석되는 방식에 집중해 볼 예정입니다.

**Comment by seo-rii** [comment]
Hello JIT!

https://github.com/deepmind/s6

딥마인드에서 공개한 파이썬 JIT 컴파일러인 s6의 코드를 살펴보며 JIT가 어떻게 작동하는지 알아보기

파이썬은 정말 느린 언어다. 인터프리터 언어 중에서도 매우 느린 축에 속한다. 만일 당신이 알고리즘 문제 해결을 해 본 적이 있다면, 파이썬으로 제출했을 시 올바른 알고리즘을 작성했음에도 "Time Limit Exceed"를 본 적이 있을 것이다. 그리고 아마 당신은 한 번쯤 이런 대답을 들었을지도 모른다. "PYPY3으로 제출해보세요."

PYPY는 파이썬으로 만든 파이썬 구현체이다. 놀랍게도, 이것의 속도는 많은 경우에서 파이썬보다 몇 배는 빠르다. 느린 파이썬에서 파이썬을 돌리는 건데, 어떻게 이것이 가능한걸까? 비결은 바로 JIT에 있다. 이 문서에서는 JIT가 무엇인지, 그리고 최근 딥마인드에서 발표한 "s6"라는 라이브러리를 통해 이것을 CPython에도 적용시킬 수 있을 지 탐구해 보고자 한다.
